### PR TITLE
Added NL and FR translations; FR needs reviewing

### PR DESCRIPTION
**Pull request by PeterKawa**

### CODE REVIEW

**Comment by frodeheg** [comment]
This is awsome, thank you.

Do you think you can also update the capability + flow translations?
all located in
.homeycompose/capabilities/*.json
.homeycompose/flow/actions/*.json
.homeycompose/flow/conditions/*.json
.homeycompose/flow/triggers/*.json

and, if you wish, add your name to the
"translators" - array in .homeycompose/app.json

**Comment by frodeheg** [comment]
Seems like pull request #204 is newer than this so I guess I should close this one and merge #204 instead?

**Comment by PeterKawa** [comment]
Hold on please, Frode, I'm having troubles with the HTML parts in the JSON. Still working on it ;-)

**Comment by PeterKawa** [comment]
Hello Frode, the nl.json and fr.json can be merged, thanks. Sorry for the many patches. When I checked the languages in the app itself, I found quite a handful of various typos. And PR is new to me, and I'm a bit chaotic ;-)

**Comment by frodeheg** [comment]
I am a bit confused, I cannot see any changes since you told me to "hold on", and pull request #204 is still newer than this one. Should I close and ignore this pull request and merge #204 or should I wait for updates on this or the other pull request?

**Comment by PeterKawa** [comment]
Well that's the problem, I am new to PR, and I obviously doing something wrong here. I put them in a new branch appearantly just by editing and saving the /locale/.json files in my fork (in the browser) mentioning Peterkawa-patch-6
Screenshot from 2023-03-25 15-35-40
I obviously followed a wrong how-to. It is very hazy to me.
Do you know a easy to understand how-to?
Can I please upload the code via PM because the files I look at now, are not the recent ones! Really annoying....

**Comment by frodeheg** [comment]
I think the procedure is as follows:
1. Make sure that your cloned repository is not behind the repository you cloned from. If so, then pull in the new changes from my repository into yours (there should be a button for it in your github page https://github.com/PeterKawa/no.sparegris )
2. Make sure all your local changes are checked in to your cloned repository
3. Your repository should now show as ahead of the repository you cloned from.
4. There should now be a button to create a pull request similar to what you already did.
5. I am unsure whether or not it is possible to update a pull request or if you have to create a new one.

If you prefer you can PM the files instead, sure, then I'll just merge this one and overwrite if there are any changes.

**Pull request closed without merging**
